---
title: "data wrangling 2"
author: "Seonyoung Park (sp3804)"
date: "10/20/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(httr)
library(jsonlite)
library(rvest)

````
## Restaurant inspections
```{r}
api_url = "https://data.cityofnewyork.us/resource/43nn-pn8j.csv"
rest_inspections = GET(api_url, query = list("$limit"=50000)) %>%
  content("parsed")

```

```{r}
rest_inspections %>%
  count(boro, grade) %>%
  pivot_wider(
    names_from = grade,
    values_from = n
  )

```

```{r}
rest_inspections = 
  rest_inspections %>%
  filter(grade %in% c("A","B","C"), boro !="0")

```

Let's look at pizza places.
```{r}
## This is to see the 'exact' match; we got only 6 observations 
rest_inspections %>%
  filter(str_detect(dba, "Pizza")) %>% view()
  
rest_inspections %>%
  filter(str_detect(dba, "PIZZA")) %>% view()

rest_inspections %>%
  mutate(dba=str_to_upper(dba)) %>%
  filter(str_detect(dba, "PIZZ")) %>% view()
```

```{r}
rest_inspections %>%
  mutate(dba=str_to_upper(dba)) %>%
  filter(str_detect(dba, "PIZZ")) %>% 
  count(boro, grade) %>%
  pivot_wider(
    names_from = grade,
    values_from = n
  )
```

Switch between character <-> factor, and plot
```{r}
# reorder "boro" setting "Manhattan" as the first (- it changes the "boro" as factor), and plot
rest_inspections %>%
  mutate(dba=str_to_upper(dba)) %>%
  filter(str_detect(dba, "PIZZ")) %>%
  mutate(boro=fct_relevel(boro, "Manhattan")) %>%
  ggplot(aes(x=boro))+geom_bar() +
  facet_wrap(. ~grade)

# reorder "boro" along the frequency (descending order) - it changes the "boro" as factor
rest_inspections %>%
  mutate(dba=str_to_upper(dba)) %>%
  filter(str_detect(dba, "PIZZ")) %>%
  mutate(boro=fct_infreq(boro)) %>%
  ggplot(aes(x=boro))+geom_bar() +
  facet_wrap(. ~grade)
```

## Napoleon Dynamite

Get some Napoleon Dynamite Amazon Review
```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(url)

review_titles = 
  dynamite_html %>%
  html_nodes(".a-text-bold span") %>%
  html_text()

review_stars = 
  dynamite_html %>%
  html_nodes(".review-rating") %>%
  html_text()

review_text = 
  dynamite_html %>%
  html_nodes(".review-text-content span") %>%
  html_text()

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)



```




